import type { Viewport } from 'next'
import { ToastContainer } from 'react-toastify'

import 'react-toastify/dist/ReactToastify.min.css'
import '@/styles/globals.css'

const DEFAULT_TITLE = '5x5'

export const metadata = {
  manifest: '/manifest.json',
  description: 'Generated by create-t3-app',
  icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
    apple: '/icon.png',
  },
  title: DEFAULT_TITLE,
}

export const viewport: Viewport = {
  themeColor: '#15232d',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='bg-cb-dark-blue text-cb-white flex min-h-screen flex-col'>
          <ToastContainer
            autoClose={2000}
            toastClassName='bg-cb-off-blue text-cb-white rounded-lg'
            bodyClassName=''
            pauseOnFocusLoss={false}
          />
          {children}
        </div>
      </body>
    </html>
  )
}
